In [135]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [99]:
df=pd.read_csv("loan.csv")

In [154]:
c=df.dropna()

In [90]:
df.groupby(["Loan_Term"]).agg({"Loan_Term":"count"})

           Loan_Term
Loan_Term
12.0             142
24.0             135
36.0             122
48.0             148
60.0             131
72.0             129
84.0             143

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        1000 non-null   int64
 1   Applicant_Income    1000 non-null   float64
 2   Coapplicant_Income  1000 non-null   float64
 3   Employment_Status   1000 non-null   object
 4   Age                 1000 non-null   float64
 5   Marital_Status      1000 non-null   object
 6   Dependents          1000 non-null   float64
 7   Credit_Score        1000 non-null   float64
 8   Existing_Loans      1000 non-null   float64
 9   DTI_Ratio           1000 non-null   float64
 10  Savings             1000 non-null   float64
 11  Collateral_Value    1000 non-null   float64
 12  Loan_Amount         1000 non-null   float64
 13  Loan_Term           1000 non-null   float64
 14  Loan_Purpose        1000 non-null   object
 15  Property_Area       1000 non-null   object
 16  Education_Level     1000 non-null   object
 17  Gender              1000 non-null   object
 18  Employer_Category   1000 non-null   object
 19  Loan_Approved       950 non-null    float64
dtypes: float64(12), int64(1), object(7)
memory usage: 156.4+ KB

In [44]:
df.describe()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Approved
count,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000
mean,501.220000,10852.571579,5082.455789,39.971579,1.474737,676.033684,1.950526,0.347263,9940.452632,24802.792632,20522.825263,48.000000,0.313684
std,289.608451,5061.632859,2943.161570,11.139797,1.105067,71.346015,1.406246,0.144341,5860.736885,14345.696031,11504.142575,24.245322,0.464234
min,1.000000,2009.000000,1.000000,21.000000,0.000000,550.000000,0.000000,0.100000,65.000000,36.000000,1015.000000,12.000000,0.000000
25%,250.250000,6730.750000,2472.750000,30.250000,1.000000,616.250000,1.000000,0.220000,4760.250000,12698.250000,9806.250000,24.000000,0.000000
50%,499.500000,10548.000000,5205.500000,40.000000,1.000000,678.000000,2.000000,0.340000,9880.500000,24321.000000,21210.500000,48.000000,0.000000
75%,752.750000,15190.000000,7620.750000,49.000000,2.000000,737.000000,3.000000,0.480000,15074.500000,36947.000000,30263.000000,72.000000,1.000000
max,1000.000000,19988.000000,9996.000000,59.000000,3.000000,799.000000,4.000000,0.600000,19996.000000,49954.000000,39995.000000,84.000000,1.000000

In [102]:
df["Applicant_ID"]=df.index+1

In [117]:
df["Loan_Purpose"]=df["Loan_Purpose"].bfill()

In [122]:
df["Loan_Purpose"]=df["Loan_Purpose"].bfill()

In [131]:
df["Education_Level"]=df["Education_Level"].bfill()

In [132]:
df["Gender"]=df["Gender"].ffill()

In [125]:
df["Employer_Category"]=df["Employer_Category"].bfill()

In [103]:
df["Applicant_Income"]=df["Applicant_Income"].fillna(10852.571579)

In [104]:
df["Coapplicant_Income"]=df["Coapplicant_Income"].fillna(5082.455789)

In [105]:
df["Employment_Status"]=df["Employment_Status"].fillna("Salaried")

In [106]:
df["Age"]=df["Age"].fillna(39)

In [107]:
df["Marital_Status"]=df["Marital_Status"].fillna("Married")

In [129]:
df["Dependents"]=df["Dependents"].fillna(0)

In [108]:
df["Credit_Score"]=df["Credit_Score"].fillna(676.033684)

In [109]:
df["Existing_Loans"]=df["Existing_Loans"].fillna(1)

In [110]:
df["DTI_Ratio"]=df["DTI_Ratio"].fillna(0.347263)

In [111]:
df["Savings"]=df["Savings"].fillna(9940.452632)

In [112]:
df["Collateral_Value"]=df["Collateral_Value"].fillna(24802.792632)

In [113]:
df["Loan_Amount"]=df["Loan_Amount"].fillna(20522.825263)

In [ ]:
df["Loan_Approved"]=df["Loan_Approved"].fillna(0)

In [114]:
df["Loan_Term"]=df["Loan_Term"].fillna(48)

In [115]:
df["Loan_Approved"]=df["Loan_Approved"].map({"Yes":1,"No":0})

In [41]:
df.corr(numeric_only=True)["Loan_Approved"].sort_values()

DTI_Ratio            -0.472434
Loan_Amount          -0.130477
Loan_Term            -0.092600
Existing_Loans       -0.036184
Age                  -0.028058
Savings              -0.017319
Dependents           -0.016541
Applicant_ID         -0.005508
Coapplicant_Income    0.009340
Collateral_Value      0.028128
Applicant_Income      0.127922
Credit_Score          0.489880
Loan_Approved         1.000000
Name: Loan_Approved, dtype: float64

In [153]:
le=LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])
df["Marital_Status"]=le.fit_transform(df["Marital_Status"])
df["Property_Area"]=le.fit_transform(df["Property_Area"])
df["Education_Level"]=le.fit_transform(df["Education_Level"])
df["Employer_Category"]=le.fit_transform(df["Employer_Category"])
df["Employer_Category"]=le.fit_transform(df["Employer_Category"])
df["Loan_Purpose"]=le.fit_transform(df["Loan_Purpose"])

In [165]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score

In [173]:
X=c.drop("Loan_Approved",axis=1)
y=c["Loan_Approved"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=31)

In [178]:
ss=StandardScaler()
X_trains=ss.fit_transform(X_train)
X_tests=ss.transform(X_test)

In [179]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [180]:
y_pred=lr.predict(X_test)
a=accuracy_score(y_test,y_pred)
p=precision_score(y_test,y_pred)
print(a)
print(p)

0.8315789473684211
0.7096774193548387

In [183]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=9)
knn.fit(X_trains,y_train)
y_pred=knn.predict(X_tests)
a1=accuracy_score(y_test,y_pred)
p1=precision_score(y_test,y_pred)
print(a1)
print(p1)

0.8052631578947368
0.6981132075471698

In [188]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_trains,y_train)
y_pred=nb.predict(X_tests)
a1=accuracy_score(y_test,y_pred)
p1=precision_score(y_test,y_pred)
print(a1)
print(p1)

0.8421052631578947
0.78

In [143]:
df.sample(20)

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
163,164,3930.000000,5468.0,2,54.0,0,0.0,715.000000,2.0,0.45,4370.000000,14676.000000,18488.000000,36.0,Education,1,0,1,3,0.0
498,499,15428.000000,2356.0,1,41.0,0,0.0,745.000000,1.0,0.31,15257.000000,12468.000000,23161.000000,24.0,Education,2,0,1,3,1.0
330,331,7177.000000,7491.0,0,38.0,0,1.0,676.033684,1.0,0.39,16537.000000,29263.000000,39796.000000,48.0,Personal,1,0,0,3,0.0
404,405,13338.000000,2946.0,2,39.0,1,0.0,641.000000,4.0,0.22,18767.000000,16360.000000,1666.000000,24.0,Car,0,0,0,1,0.0
999,1000,13093.000000,2385.0,1,23.0,0,1.0,613.000000,3.0,0.32,12436.000000,25816.000000,35818.000000,48.0,Personal,1,0,1,3,0.0
970,971,17149.000000,9011.0,0,58.0,1,2.0,550.000000,2.0,0.59,5153.000000,24578.000000,19413.000000,36.0,Education,0,0,1,0,0.0
618,619,7569.000000,9400.0,1,35.0,1,1.0,743.000000,0.0,0.43,1550.000000,44132.000000,34077.000000,72.0,Car,1,1,1,3,0.0
749,750,14819.000000,5047.0,3,58.0,1,3.0,676.033684,1.0,0.31,18050.000000,48651.000000,18996.000000,24.0,Business,0,1,1,2,0.0
72,73,18216.000000,7101.0,1,29.0,0,3.0,565.000000,4.0,0.20,15856.000000,24802.792632,28873.000000,12.0,Education,2,0,1,1,0.0
706,707,14199.000000,4760.0,1,58.0,0,3.0,704.000000,3.0,0.45,1461.000000,36587.000000,26594.000000,72.0,Personal,2,0,1,1,0.0
406,407,9543.000000,526.0,2,39.0,0,2.0,629.000000,2.0,0.53,5876.000000,36843.000000,28883.000000,24.0,Car,2,1,0,1,0.0
190,191,16075.000000,2050.0,2,33.0,0,3.0,629.000000,4.0,0.28,8572.000000,15487.000000,22556.000000,24.0,Education,1,0,1,0,0.0
763,764,18644.000000,3097.0,1,23.0,0,3.0,733.000000,4.0,0.34,13833.000000,36295.000000,10982.000000,24.0,Education,2,1,0,3,1.0
828,829,4243.000000,7397.0,1,42.0,0,2.0,672.000000,3.0,0.51,9940.452632,4327.000000,39255.000000,60.0,Home,2,0,1,0,0.0
36,37,10433.000000,6136.0,3,24.0,0,0.0,798.000000,1.0,0.13,15225.000000,49063.000000,8919.000000,36.0,Business,2,0,1,2,1.0
334,335,3150.000000,9077.0,1,49.0,0,3.0,721.000000,1.0,0.44,1284.000000,23383.000000,18256.000000,48.0,Education,2,1,0,2,0.0
792,793,2077.000000,7622.0,2,45.0,0,0.0,619.000000,3.0,0.57,18214.000000,47605.000000,39749.000000,60.0,Home,0,0,1,3,0.0
186,187,8616.000000,8190.0,0,32.0,0,0.0,795.000000,1.0,0.56,10207.000000,28488.000000,8741.000000,12.0,Education,2,1,0,2,0.0
928,929,10852.571579,2964.0,3,43.0,0,2.0,679.000000,4.0,0.57,17206.000000,45592.000000,9212.000000,72.0,Business,0,0,0,0,0.0
367,368,9390.000000,5658.0,3,39.0,0,1.0,558.000000,1.0,0.13,17165.000000,24364.000000,20522.825263,72.0,Home,2,0,1,0,0.0